### ISSUE TITLE
Storyblok CLI cannot access spaces whose server location is US

### ISSUE THREAD

**Issue by lanelps** [storyblok/storyblok-cli#12]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [x] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**
Using the Storyblok CLI version 3.10.5 `spaces` command, I am only able to see spaces whose server location is EU.

**Expected behavior:**
I would expect to see all spaces associated to my account, regardless of whether it's server location is EU or US based.
I currently have 6 spaces associated with my account. 3 are EU based, and 3 are US based. Only the ones in the EU are listed in the command prompt

**Steps to replicate**
Login in to your Storyblok account `storyblok login`, then list all the spaces associated with your account `storyblok spaces`

**Comment by bryanmig** [comment]
I am also experiencing this issue which is a blocker for my team.  I have created PR storyblok/storyblok#837 which adds a new flag that allows the CLI to work with US sites.

**Comment by ademarCardoso** [comment]
@lanelps @bryanmig 
Thanks for the collaboration, we solved the region problems and about the spaces command, now it lists all existing spaces in `US` and `EU`.
Sorry for the delay in resolving this and thank you for your cooperation.
PS: I'll close the issue because I believe the problem has been resolved, if not, we can reopen or open a new one to investigate the problem. Thank you one more time.
