### ISSUE TITLE
Misleading Two-Factor Authentication Prompt in CLI Login

### ISSUE THREAD

**Issue by joerncodes** [storyblok/storyblok-cli#138]
**Current behavior:**

When attempting to log in using the Storyblok CLI, when you have two-factor authentication activated, the message displayed reads: `"We sent you a code to your email / phone, please insert the authentication code."`
This occurs even when two-factor authentication is **set to use an authenticator application**. The prompt does not mention an authenticator application, which is misleading.

**Expected behavior:**

The CLI should display a message accurately reflecting the configured two-factor authentication method. If an authenticator application is configured, the message should guide the user to retrieve the code from their authenticator app instead of referring to `email / phone`.

**Steps to reproduce:**

- Configure your Storyblok account with two-factor authentication via an authenticator application.
- `storyblok login`

**Related code:**

None

**Other information:**

![image](https://github.com/user-attachments/assets/ab013bfd-0da0-4449-b64c-014270dd8a02)

![image psd(1)](https://github.com/user-attachments/assets/1646df62-bad9-407a-86e2-bfd2748a8b40)

**Comment by alvarosabu** [comment]
Hi @joerncodes thanks for opening this issue. We have updated the message for the upcoming v4 of the CLI. 

#118 

https://github.com/storyblok/storyblok-cli/blob/6ee6107d6e1406a5e2cb954b5d6e78f372ed4385/src/commands/login/index.ts#L116-L119

I will close this issue since it has been addressed for the upcoming major version. Thanks
