### ISSUE TITLE
Pull-components --separate-files flag mix/overwrites presets and components

### ISSUE THREAD

**Issue by edv-ns** [storyblok/storyblok-cli#47]
**Current behavior:**

When running `storyblok pull-components` with a `--separate-files` flag enabled, it seems `hero` block and `Hero` preset are overwritten on each other.

https://github.com/storyblok/storyblok-cli/blob/master/src/tasks/pull-components.js#L55

**Expected behavior:**

- The presets and block library items are not mixed.
- The presets does not override the block json data

Ideally I would follow the same pattern as with non-separate where we get 2 files: 
```
components.<SPACE_ID>.json
presets.<SPACE_ID>.json
```

but make it into multiple files
```
components
  hero-<SPACE_ID>.json
presets
  Hero-<SPACE_ID>.json
```

**Steps to reproduce:**

1. add `hero` block to block library
2. add `section` block to block library + add preset called `Hero`

![image](https://github.com/storyblok/storyblok-cli/assets/73230019/6d55abe1-00d7-4f27-b53d-76344ca3a030)

![image](https://github.com/storyblok/storyblok-cli/assets/73230019/4b0c4476-b249-4a20-a710-3f4aa8876a33)

3. Run cli command: `storyblok pull-components --space <SPACE_ID> --separate-files`
4. check overwriten file `hero-<SPACE_ID>.json` containing **preset** data and not the block schema.

**Related code:**

Checking the source code https://github.com/storyblok/storyblok-cli/blob/master/src/tasks/pull-components.js#L55 and it seems it indeed creates a precedence to mix `hero` block with `Hero` preset, where preset json overrides the block json one.

**Comment by ademarCardoso** [comment]
Thanks to reporting this problem, i will take a look on that.

**Comment by Edo-San** [comment]
Hey @edv-ns 👋 
FYI some time ago we released a fix for this issue, you can find more about it [on the readme](https://github.com/storyblok/storyblok-cli?tab=readme-ov-file#pull-components)
As you pointed out, the issue was related to file names of components and presets that were handled exactly in the same way. This led to some quirks with the async write calls where files that shared the same name got overwritten multiple times in the process.
You can now use the flag `--prefix-presets-names` so that the preset schema file names will be prefixed with the component name, effectively creating a sort of "composite primary key" `{componentName}-{presetName}`.

Again, thanks for pointing this out and for helping us to make Storyblok "a better place"! 🙌

**Comment by edvinasjurele** [comment]
Thank you a lot for the solution to this! @Edo-San
